### ISSUE TITLE
First issues

### ISSUE THREAD

**Issue by inmyth** [Pirat4e/KinoApplication#1]
You get the null error because you forgot to initiate `mActivity`. Just remove it and use `this` instead. Also you need to initialize ViewHolder with the relevant View. 

```java
class ViewHolder{
 public TextView text;
 ...
  public ViewHolder(View convertView){
     text = convertView.findViewById(R.id.txt_tittle);
     ...
  }
}

```

and do it in your adapter like viewHolder = new ViewHolder(convertView);

**Comment by Pirat4e** [comment]
Made the changes, now the debugger goes even further to [line](https://github.com/Pirat4e/KinoApplication/blob/new/app/src/main/java/com/empire/kinoapplication/MainActivity.java#L42) skiping the parsing and it moves to [line](https://github.com/Pirat4e/KinoApplication/blob/new/app/src/main/java/com/empire/kinoapplication/MainActivity.java#L51) giving an error msg

**Comment by inmyth** [comment]
What does the error say ? If the debugger gets inside onErrorResponse method then it is almost certain the problem lies with your server or that you forgot to change the url http://example.com

**Comment by Pirat4e** [comment]
`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.empire.kinoapplication/com.empire.kinoapplication.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.empire.kinoapplication.AppController.addToRequestQueue(com.android.volley.Request)' on a null object reference` this is what I get in the logcat. I think the server is fine, because I have tried it before, you can have a look at [it](http://3dkinobitola.com/?json=get_category_posts&slug=Repertoar&status=publish)

**Comment by Pirat4e** [comment]
I made some changes and added the [request method](https://github.com/Pirat4e/KinoApplication/blob/new/app/src/main/java/com/empire/kinoapplication/MainActivity.java#L41), but still giving the same error. Maybe there is something missing in the [AppController](https://github.com/Pirat4e/KinoApplication/blob/new/app/src/main/java/com/empire/kinoapplication/AppController.java)?

**Comment by inmyth** [comment]
You need to add that ApplicationController in the Manifest like this
````java
    <application
        android:name="com.empire.kinoapplication.MyApplication"
````

**Comment by Pirat4e** [comment]
its getting the data now, but crashing after this [line](https://github.com/Pirat4e/KinoApplication/blob/new/app/src/main/java/com/empire/kinoapplication/MainActivity.java#L49)

**Comment by inmyth** [comment]
What does the error say ? You need to debug onResponse and check  String response and Wrap wrap.

**Comment by inmyth** [comment]
What does the error say ? You need to debug onResponse and check String response and Wrap wrap.

**Comment by Pirat4e** [comment]
I am passing the data that i want. but I dont think im passing the arraylist to the adapter, Do you think I have to change my constructor in [KinoAdapter](https://github.com/Pirat4e/KinoApplication/blob/new/app/src/main/java/com/empire/kinoapplication/adapter/KinoAdapter.java)

**Comment by Pirat4e** [comment]
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference at com.empire.kinoapplication.MainActivity$1.onResponse(MainActivity.java:53)
            at com.empire.kinoapplication.MainActivity$1.onResponse(MainActivity.java:45)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:60)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)`  this is my logcat

**Comment by inmyth** [comment]
No you just have not initialized ArrayList<Post> arrayList; in the Activity

**Comment by Pirat4e** [comment]
I made some changes in the [MainActivity](https://github.com/Pirat4e/KinoApplication/blob/new/app/src/main/java/com/empire/kinoapplication/adapter/KinoAdapter.java)  but still getting this in logcat `java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference`

**Comment by inmyth** [comment]
You just need to do this `ArrayList<Post> arrayList = new ArrayList<>(); `

**Comment by Pirat4e** [comment]
made the [change](https://github.com/Pirat4e/KinoApplication/blob/new/app/src/main/java/com/empire/kinoapplication/MainActivity.java#L49), but it's saying `Contents of collection 'arrayList' are updated, but never queried`

**Comment by Pirat4e** [comment]
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference
            at com.empire.kinoapplication.MainActivity$1.onResponse(MainActivity.java:54)
            at com.empire.kinoapplication.MainActivity$1.onResponse(MainActivity.java:45)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:60)
            at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
            at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)`  this is the logcat

**Comment by inmyth** [comment]
Just remove these 
````java
                              ArrayList<Post> arrayList = new ArrayList<>();
                              arrayList.add(post);
````
and replace them with adapter.add(post);

**Comment by Pirat4e** [comment]
now i get this `java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
            at android.view.LayoutInflater.from(LayoutInflater.java:219)
            at com.empire.kinoapplication.adapter.KinoAdapter.getView(KinoAdapter.java:39)
            at android.widget.AbsListView.obtainView(AbsListView.java:2344)
            at android.widget.ListView.makeAndAddView(ListView.java:1864)
            at android.widget.ListView.fillDown(ListView.java:698)
            at android.widget.ListView.fillFromTop(ListView.java:759)
            at android.widget.ListView.layoutChildren(ListView.java:1659)
            at android.widget.AbsListView.onLayout(AbsListView.java:2148)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:502)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:15596)
            at android.view.ViewGroup.layout(ViewGroup.java:4966)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)`

**Comment by inmyth** [comment]
What is line 39 in KinoAdapter ? Is this code the latest ?

**Comment by Pirat4e** [comment]
this is line [39](https://github.com/Pirat4e/KinoApplication/blob/new/app/src/main/java/com/empire/kinoapplication/adapter/KinoAdapter.java#L39) yeah its the latest

**Comment by inmyth** [comment]
Remove `Context context;` from the adapter.

Replace 34 with `rowView = LayoutInflater.from(getContext()).inflate(R.layout.list_item_view, null);`

remove 36, 37
and remove `View rowView = convertView;`. This line is useless. Just use `convertView`

**Comment by Pirat4e** [comment]
That worked perfect! I tried implementing this same approach with another [app](https://github.com/Pirat4e/KinoNewApplication) with Sliding Tabs, but its weird and I'm only getting the last request it made, When i was working with the AsyncTask(that's how I started) every tab was working on its own. With Volley everything is merged.. i think. I really have no idea what's going on. cant find any example similar to my app. [Tab1](https://github.com/Pirat4e/KinoNewApplication/blob/master/app/src/main/java/com/empire/kinonewapplication/RepertoireTab.java#L29) [Tab2](https://github.com/Pirat4e/KinoNewApplication/blob/master/app/src/main/java/com/empire/kinonewapplication/SoonTab.java#L29) [Tab3](https://github.com/Pirat4e/KinoNewApplication/blob/master/app/src/main/java/com/empire/kinonewapplication/ArchiveTab.java#L29) I tried adding two more adapters with three different layouts, but it didnt work, I tried changing the StringRequest's [name](https://github.com/Pirat4e/KinoNewApplication/blob/master/app/src/main/java/com/empire/kinonewapplication/ArchiveTab.java#L54) on every tab, that didn't work either. So I think I have to make so changes to the [AppController](https://github.com/Pirat4e/KinoNewApplication/blob/master/app/src/main/java/com/empire/kinonewapplication/Controller/AppController.java)  but I really don't know what to change and how.

**Comment by Pirat4e** [comment]
I read something about synchronous and asynchronous requests on Volley, I think Synchronous request is the way to go, but I don't know how to implement it with Volley.

**Comment by Pirat4e** [comment]
Solved it. I had to add listView = getListView();

**Comment by inmyth** [comment]
It is good that it works. You are developing so you will have many problems. I cannot help you always but I hope my help can help you solve similar problems. You have null pointer exception problems many times so you should check your object references more. If you have different problem then you should post it in SO. This place is actually intended for a specific issue so if it's solved then you should close it.

**Comment by Pirat4e** [comment]
ok , thanks again. Ill keep in mind everything that you said
